export ParamBox, inValOf, inSymOf, inSymValOf, outValOf, outSymOf, dataOf, mapOf, 
       outValCopy, inVarCopy, enableDiff!, disableDiff!, isDiffParam, toggleDiff!

using Symbolics: Num

"""

    ParamBox{T, V, F} <: DifferentiableParameter{ParamBox, T}

Parameter container that can enable parameter differentiations.

≡≡≡ Field(s) ≡≡≡

`data::Array{T<:Number, 0}`: The data (parameter) stored in a 0-D `Array` that can be 
accessed by syntax `[]`.

`dataName::Symbol`: The name assigned to the stored data.

`map::Function`: The mathematical mapping of the data. The mapped result can be accessed by 
syntax `()`.

`canDiff::Array{Bool, 0}`: Indicator that whether this container (mapped variable) is 
marked as "differentiable".

`index::Array{<:Union{Int, Nothing}, 0}`: Additional index assigned to the parameter.

≡≡≡ Initialization Method(s) ≡≡≡

    ParamBox(data::Array{T, 0}, dataName::Symbol=:undef; 
             index::Union{Int, Nothing}=nothing) where {T<:Number} -> 
    ParamBox{T, dataName, :itself}

    ParamBox(data::Array{T, 0}, name::Symbol, mapFunction::Function, 
             dataName::Symbol=:undef; canDiff::Bool=true, 
             index::Union{Int, Nothing}=nothing) where {T<:Number} ->
    ParamBox{T, name, $(nameOf)(mapFunction)}

    ParamBox(data::Number, dataName::Symbol=:undef; index::Union{Int, Nothing}=nothing, 
             paramType::Type{<:Number}=Float64) where {T<:Number} -> 
    ParamBox{paramType, dataName, :itself}

    ParamBox(data::Number, name::Symbol, mapFunction::Function, dataName::Symbol=:undef; 
             canDiff::Bool=true, index::Union{Int, Nothing}=nothing, 
             paramType::Type{<:Number}=Float64) where {T<:Number} ->
    ParamBox{paramType, name, $(nameOf)(mapFunction)}

`name` specifies the name of the (mapped) variable the `ParamBox` represents, which helps 
with symbolic representation and automatic differentiation.

`mapFunction`: The (mathematical) mapping of the data, which will be stored in the field 
`map`. It is for the case where the variable represented by the `ParamBox` is dependent on 
another independent variable of which the value is the stored data in the container. After 
initializing a `ParamBox`, e.g `pb1 = ParamBox(x, mapFunction=f)`, `pb[]` returns `x`, and 
`pb()` returns `f(x)`. `mapFunction` is set to `$(itself)` in default, which is a dummy 
function that maps the data to itself.

`canDiff` determines whether the mapped math variable is "marked" as differentiable (i.e., 
the mapping is a differentiable function) with respect to the stored data. In other 
words, it determines whether the mapped variable `ParamBox` generated during the automatic 
differentiation procedure is treated as a dependent variable or an independent variable 
regardless of the mapping relation.

`paramType` specifies the type of the stored parameter to avoid data type mutation.

≡≡≡ Example(s) ≡≡≡

```jldoctest; setup = :(push!(LOAD_PATH, "../../src/"); using Quiqbox)
julia> ParamBox(1.0)
ParamBox{Float64, :undef, :itself}(1.0)[∂][undef]

julia> ParamBox(1.0, :a)
ParamBox{Float64, :a, :itself}(1.0)[∂][a]

julia> ParamBox(1.0, :a, abs)
ParamBox{Float64, :a, :abs}(1.0)[∂][x_a]
```

**NOTE 1:** The rightmost "`[∂][IV]`" in the printing info indicates the differentiability 
and the name of the represented independent variable `:IV`. When the `ParamBox` is marked 
as a "differentiable function", "`[∂]`" is in color green (otherwise it's in grey).

**NOTE 2:** It's always the (mapped) variable `V` generated by a `ParamBox{<:Any, V}` that 
is used to construct a basis, whereas the underlying independent variable is used to 
differentiate the basis (in other words, only when `mapFunction = $(itself)` or 
`canDiff = false` is the independent variable same as the mapped variable/represented 
parameter).
"""
struct ParamBox{T, V, F} <: DifferentiableParameter{ParamBox, T}
    data::Array{T, 0}
    dataName::Symbol
    map::Function
    canDiff::Array{Bool, 0}
    index::Array{<:Union{Int, Nothing}, 0}

    function ParamBox{V, F}(data::Array{T, 0}, index, canDiff, dataName=:undef) where 
                           {V, F, T}
        dName = (dataName == :undef) ? Symbol("x_" * string(V)) : dataName
        new{T, V, F}(data, dName, getFunc(Val(F)), canDiff, index)
    end

    ParamBox{V, :itself}(data::Array{T, 0}, index) where {V, T} = 
    new{T, V, :itself}(data, V, itself, fill(false), index)
end

function ParamBox{V}(mapFunction::F, 
                     data::Array{T, 0}, index, canDiff, dataName=:undef) where 
                    {V, F<:Function, T}
    fSym = mapFunction |> nameOf
    fStr = fSym |> string
    if startswith(fStr, '#')
        idx = parse(Int, fStr[2:end])
        fSym = "f_" * string(V) * numToSubs(idx) |> Symbol
        renameFunc(fSym, mapFunction)
    end
    ParamBox{V}(FunctionType{fSym}(), data, index, canDiff, dataName)
end

ParamBox{V}(::FunctionType{F}, data::Array{T, 0}, index, canDiff, dataName=:undef) where 
           {V, T, F} = 
ParamBox{V, F}(data, index, canDiff, dataName)

ParamBox{V}(::FunctionType{:itself}, data::Array{T, 0}, index, _...) where {V, T} = 
ParamBox{V, :itself}(data, index)

ParamBox{V}(pb::ParamBox{<:Any, <:Any, F}) where {V, F} = 
ParamBox{V}(FunctionType{F}(), pb.data, pb.index, pb.canDiff, pb.dataName)

function ParamBox{V}(arg, data::Number, args...; 
                     paramType::Type{<:Number}=Float64, roundDigits::Int=-1) where {V}
    num = (roundDigits < 0 ? data : round(data, digits=roundDigits)) |> paramType
    ParamBox{V}(arg, fill(num), args...)
end

ParamBox(data::T; index::Union{Int, Nothing}=nothing) where {T} = 
ParamBox{:undef}(FunctionType{:itself}(), data, genIndex(index))

ParamBox(data::T, dataName::Symbol; index::Union{Int, Nothing}=nothing) where {T} = 
ParamBox{dataName}(FunctionType{:itself}(), data, genIndex(index))

ParamBox(data::T, name::Symbol, mapFunction::F, dataName::Symbol=:undef; 
         canDiff::Bool=true, index::Union{Int, Nothing}=nothing) where {T, F<:Function} = 
ParamBox{name}(mapFunction, data, genIndex(index), fill(canDiff), dataName)


"""

    inValOf(pb::ParamBox) -> Number

Return the value of stored data (independent variable) of the input `ParamBox`. Equivalent 
to `pb[]`.
"""
@inline inValOf(pb::ParamBox{T}) where {T} = pb.data[]::T


"""

    inSymOf(pb::ParamBox) -> Symbolics.Num

Return the variable`::Symbolics.Num` of stored data (independent variable) of the input 
`ParamBox`.
"""
@inline function inSymOf(pb::ParamBox{T}) where {T}
    idx = pb.index[]
    hasIdx = idx isa Int
    ivSym = inSymOfCore(pb)
    hasIdx ? Symbolics.variable(ivSym, idx) : Symbolics.variable(ivSym)
end


"""

    inSymValOf(pb::ParamBox{T}) where {T} -> ::Pair{Symbolics.Num, T}

Return a `Pair` of the stored independent variable of the input `ParamBox` and its 
corresponding value.
"""
@inline inSymValOf(pb::ParamBox{T}) where {T} = (inSymOf(pb) => pb.data[])::Pair{Symbolics.Num, T}


"""

    outValOf(pb::ParamBox) -> Number

Return the value of mapped data (dependent variable) of the input `ParamBox`. Equivalent to 
`pb()`.
"""
@inline outValOf(pb::ParamBox{T}) where {T} = pb.map(pb.data[]::T)

@inline outValOf(pb::ParamBox{T, <:Any, :itself}) where {T} = inValOf(pb)

(pb::ParamBox)() = outValOf(pb)
# (pb::ParamBox)() = Base.invokelatest(pb.map, pb.data[])::Float64


"""

    outSymOf(pb::ParamBox) -> Symbolics.Num

Return the variable`::Symbolics.Num` of mapped data (dependent variable) of the input 
`ParamBox`.
"""
@inline outSymOf(pb::ParamBox{T, <:Any, itself}) where {T} = inSymOf(pb)

@inline function outSymOf(pb::ParamBox)
    idx = pb.index[]
    hasIdx = idx isa Int
    vSym = outSymOfCore(pb)
    hasIdx ? Symbolics.variable(vSym, idx) : Symbolics.variable(vSym)
end


"""

    inSymOfCore(pb::ParamBox) -> Symbol

Return the `Symbol` of the stored data (independent variable) of the input `ParamBox`.
"""
@inline inSymOfCore(pb::ParamBox) = pb.dataName


"""

    outSymOfCore(pb::ParamBox) -> Symbol

Return the `Symbol` of the mapped data (dependent variable) of the input `ParamBox`.
"""
@inline outSymOfCore(::ParamBox{<:Any, V}) where {V} = V


"""

    dataOf(pb::ParamBox{T}) where {T<:Number} -> Array{T, 0}

Return the 0-D `Array` of the data stored in the input `ParamBox`.
"""
@inline dataOf(pb::ParamBox) = pb.data


"""

    mapOf(pb::ParamBox{<:Number, F}) where {F<:Function} -> F

Return the mapping function of the input `ParamBox`.
"""
@inline mapOf(pb::ParamBox) = pb.map


"""

    outValCopy(pb::ParamBox{<:Number, V}) -> ParamBox{<:Number, V, :itself}

Return a new `ParamBox` of which the stored data is a **deep copy** of the mapped data from 
the input `ParamBox`.
"""
outValCopy(pb::ParamBox{T, V}) where {T, V} = 
ParamBox{V, :itself}(fill(pb()), genIndex(nothing))


"""

    inVarCopy(pb::ParamBox) -> ParamBox{<:Number, <:Any, :itself}

Return a new `ParamBox` of which the stored data is a **shallow copy** of the stored data 
from the input `ParamBox`.

≡≡≡ Example(s) ≡≡≡

```jldoctest; setup = :(push!(LOAD_PATH, "../../src/"); using Quiqbox)
julia> pb1 = ParamBox(-2.0, :a, abs)
ParamBox{Float64, :a, :abs}(-2.0)[∂][x_a]

julia> pb2 = inVarCopy(pb1)
ParamBox{Float64, :x_a, :itself}(-2.0)[∂][x_a]

julia> pb1[] == pb2[] == -2.0
true

julia> pb1[] = 1.1
1.1

julia> pb2[]
1.1
```
"""
inVarCopy(pb::ParamBox{T}) where {T} = 
ParamBox{inSymOfCore(pb), :itself}(pb.data, genIndex(nothing))


const NoDiffMark = superscriptSym['!']


"""

    enableDiff!(pb::ParamBox) -> ParamBox

Mark the input `ParamBox` as "differentiable" and return the marked `ParamBox`.
"""
function enableDiff!(pb::ParamBox)
    pb.canDiff[] = true
    pb
end


"""

    disableDiff!(pb::ParamBox) -> ParamBox

Mark the input `ParamBox` as "non-differentiable" and return the marked `ParamBox`.
"""
function disableDiff!(pb::ParamBox)
    pb.canDiff[] = false
    pb
end


"""

    isDiffParam(pb::ParamBox) -> Bool

Return the Boolean value of if the input `ParamBox` is "differentiable".
"""
isDiffParam(pb::ParamBox) = pb.canDiff[]


"""

    toggleDiff!(pb::ParamBox) -> Bool

Toggle the differentiability (`pb.canDiff[]`) of the input `ParamBox` and return the 
altered result.
"""
toggleDiff!(pb::ParamBox) = begin pb.canDiff[] = !pb.canDiff[] end